### ISSUE TITLE
Keyspace don't open

### ISSUE THREAD

**Issue by gitcarky** [Keyspace-cloud/android#13]
I installed **Keyspace** to see how it works, but of the three attempts (_in 3 months_) I made to try to open it, none worked.

I think it's the **miui system** that's getting in the way.

**Comment by Wjxfi** [comment]
Same (miui 13.0.5, poco x3 pro, android 12, f-droid latest)
![316078.jpg](https://user-images.githubusercontent.com/113500363/219870246-afa73e7f-89b1-490b-8ae9-0bd8f2c5057a.jpg)

**Comment by Wjxfi** [comment]
@4f77616973 will you fix it?

**Comment by Wjxfi** [comment]
Reopen this please
