### ISSUE TITLE
How delete account / will there be a self host server like bitwarden

### ISSUE THREAD

**Issue by yremac** [Keyspace-cloud/android#15]
How delete account / 
will there be a self host server like bitwarden?

**Comment by 4f77616973** [comment]
> How delete account

You can email us at info@keyspace.cloud with the subject "Account deletion". We will be adding this functionality within the app soon to ease the deletion process.

> will there be a self host server like bitwarden?

It's not on the roadmap at the moment, but we may explore this further in the future.
