### ISSUE TITLE
Many questions

### ISSUE THREAD

**Issue by Terkyz** [Keyspace-cloud/android#2]
I recently found out about this awesome app on Neo-Store, but I was not able to find practically no information about it, besides the official website and Keyspace page, could someone explain me a little bit? Is

it planned to be a membership service? Is there a desktop version or web only? Is the notes section planned to be an advanced notes app like Joplin or just an additional section?

**Comment by nimish-ks** [comment]
Hi @Terkyz,

We are in the process of updating the keyspace.cloud page with more detailed and up to date info. 

Keyspace is a secure digital wallet to create, store and sync your logins, notes and payment info. We have plans to expand this beyond just the scope of password manager features. We will share a roadmap soon.

Its a free service. We will eventually add pro features that users may choose to pay for.

Currently you can access the web app on https://app.keyspace.cloud/ (You will have to have created an account on your mobile app first)

We have a browser extension as well as desktop apps in the works. Coming out in a few days. Stay tuned!

The notes is a sub-section which has full markdown support.

If you have any further question, you can reach out to us on our discord: https://discord.gg/RRhgbNTa

Any feedback you may have is also appreciated! Cheers

**Comment by Terkyz** [comment]
Good to know, I will keep an eye on the project and try to give as much feedback as possible!
