### ISSUE TITLE
App is force stopping and auto closing

### ISSUE THREAD

**Issue by krushnadeore** [Keyspace-cloud/android#4]
latest version on android 13 after unlocking app using fingerprint its says like xchacha sync and the auto closing itself 
I will try to send logs next time

**Comment by krushnadeore** [comment]
> Hi @krushnadeore
> 
> Does this happen after the first ever biometric prompt during account creation or while unlocking the app after having created an account?

After unlocking

**Comment by nimish-ks** [comment]
Could you provide us with your device details? (Handset, Hardware, Operating system, Biometic support, Screen lock status)

We are planning to add a debug log export feature in the next release which should help with investigations of such bugs.

Meanwhile are you able unlock the app at all?

We do not have plans to support other symmetric ciphers. We have picked XChaCha20-Poly1305 for its security and performance.
More specifically ChaCha provides AEAD which provides confidentiality and authenticity of data. Our implementation uses 256 bit keys along with 192 bit extended nonces for better security.

More info: 
[AEAD - Authenticated encryption](https://en.wikipedia.org/wiki/Authenticated_encryption)
[Libsodium docs](https://doc.libsodium.org/secret-key_cryptography/aead/chacha20-poly1305/xchacha20-poly1305_construction)
[ChaCha20-Poly1305 Wikipedia](https://en.wikipedia.org/wiki/ChaCha20-Poly1305)
