### ISSUE TITLE
Increase card digits maximum limit

### ISSUE THREAD

**Issue by silvzr** [Keyspace-cloud/android#44]
### Summary

Hi, I would like to request an increase in the maximum number of digits available for cards, which is 16 as of now. In fact my debit card has 19 digits so unfortunately I'm unable to add it.
Thanks in advance

### Basic Example

Take a 16+ digits number card
Try to insert it in the app
Observe that you won't be able to

**Comment by nimish-ks** [comment]
Hi @silvzr 

That's interesting. What debit card do you have?

Sure, we will increase the card digit limit in the upcoming releases. This is something we will have to coordinate with the release of web apps and browser extensions as well. https://github.com/Keyspace-cloud/web

Should be easy enough.

Thanks for pointing it out. Cheers

**Comment by silvzr** [comment]
My debit card is prolly something related to my country, as it's not MasterCard or Visa either but "Maestro". Checking their website they say that their cards digits may vary from 13 to 19
