### ISSUE TITLE
Auto fill passwords

### ISSUE THREAD

**Issue by candroid-man** [Keyspace-cloud/android#7]
I'm thinking that this app could be a password manager to compete with Bitwarden and KeePass. Then create a browser extension for it and then your entire digital life would be available on Keyspace. I hope this is the direction you plan to go in, I'm very excited to see where this goes and I will be following this project closely

**Comment by nimish-ks** [comment]
Hello @candroid-man!

Browser extension and desktop apps are currently in development. (85% done)

Autofill for the android app and browser extensions are on the roadmap.

You may also see traces of boilerplate autofill code in the repo ;) https://github.com/Keyspace-cloud/android/blob/bc89898869f24a2f3680f5d96b19518db7684edf/app/src/main/kotlin/cloud/keyspace/android/PasswordAutofill.kt

**Comment by candroid-man** [comment]
Where can I see the roadmap? Now you've got me excited 😊

**Comment by nimish-ks** [comment]
> Where can I see the roadmap? Now you've got me excited blush

https://docs.keyspace.cloud/docs/project/roadmap/
