### ISSUE TITLE
Material You 3 and additional themes

### ISSUE THREAD

**Issue by candroid-man** [Keyspace-cloud/android#8]
I love the Google-like UI Keyspace is going for, however it would be even better with Material You, as well as having the ability to change the primary color. I'd also like the option to change the dark mode from pure black to dark gray or another shade that is lighter

**Comment by 4f77616973** [comment]
Hey there, we do have plans for adding these things in the future (especially a dark/black mode toggle to prevent AMOLED smearing). But we're focusing more on the bug fixes for now. Stay tuned.
