### ISSUE TITLE
[Feature Request] Add Customize logo

### ISSUE THREAD

**Issue by PressSay** [Keyspace-cloud/android#9]
It would be great if I could add my own favorite icons!

**Comment by rohan-keyspace** [comment]
Hi @PressSay, this is coming soon!

**Comment by nimish-ks** [comment]
@PressSay 

By custom icons do you mean the ability to import custom icons (svg/png) from local storage and use for logins and cards? If yes, we do not have support for this.

If you mean the ability to set an icon that is different than of the one that's auto assigned while creating / editing a login or a card; we already have support for this.

Simply tap on the auto assigned icon while creating or editing a new login or a card. It will open a popup where you can search and select any icon.

Here is an example editing the bank icon on the cards screen:
![icon-picker](https://user-images.githubusercontent.com/85357445/208278521-e7f35a8a-e4eb-42fc-b10f-f51008b6156a.png)

**Comment by PressSay** [comment]
> @PressSay
> 
> By custom icons do you mean the ability to import custom icons (svg/png) from local storage and use for logins and cards? If yes, we do not have support for this.


yes I mean want to import my favorite (svg, png). Here I would like to ask if you are planning to develop this feature in the future ?

**Comment by nimish-ks** [comment]
> > @PressSay
> > By custom icons do you mean the ability to import custom icons (svg/png) from local storage and use for logins and cards? If yes, we do not have support for this.
> 
> yes I mean want to import my favorite (svg, png). Here I would like to ask if you are planning to develop this feature in the future ?

For the foreseeable future we don't have any plans for allowing users to pick icons from local storage.

You are welcome to contribute to our selection by creating a PR with SVGs you would like to see within the app. https://github.com/Keyspace-cloud/android/tree/bc89898869f24a2f3680f5d96b19518db7684edf/app/src/main/res/raw
